version: '3.3'
x-app: &base-app
  build:
    context: '.'
  depends_on:
    - "postgres"
    - "redis"
  env_file:
    - .env
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true

services:
  app:
    <<: *base-app
    container_name: ua_app
    entrypoint: ['/app-entrypoint.sh']
    healthcheck:
      test: "${DOCKER_WEB_HEALTHCHECK_TEST:-curl localhost:8000/check_health/}"
      interval: "60s"
      timeout: "3s"
      retries: 3
    ports:
      - "8000:8000"

  worker:
    <<: *base-app
    container_name: ua_celery
    entrypoint: [ '/celery-entrypoint.sh']
    logging:
      driver: none


  postgres:
    image: postgres:13-alpine
    container_name: ua_postgres
    logging:
      driver: none
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    build: ./redis
    container_name: ua_redis
    logging:
      driver: none
    volumes:
      - ./redis/backup:/data
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx
    container_name: ua_nginx
    depends_on:
      - app
    ports:
      - "80:80"
    restart: "on-failure"

volumes:
  postgres: { }
  redis: { }